// dummyServices.js
const DUMMY_SERVICES = [
  // ---- Ride ----
  {
    city: "Lagos",
    serviceId: "ride-uber",
    service_type: "ride",
    name: "Uber",
    vehicleTypes: ["Sedan", "SUV", "Motorbike", "Van"],
    price: 0,
    eta: "5-10 mins",
    image: null,
    metadata: { rating: 4.8, reviews: 1200 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "ride-bolt",
    service_type: "ride",
    name: "Bolt",
    vehicleTypes: ["Sedan", "SUV", "Motorbike"],
    price: 0,
    eta: "6-12 mins",
    image: null,
    metadata: { rating: 4.6, reviews: 800 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "ride-indrive",
    service_type: "ride",
    name: "inDrive",
    vehicleTypes: ["Sedan", "Motorbike"],
    price: 0,
    eta: "7-15 mins",
    image: null,
    metadata: { rating: 4.5, reviews: 500 },
    createdAt: new Date().toISOString(),
  },

  // ---- Food ----
  {
    city: "Lagos",
    serviceId: "food-dominos",
    service_type: "food",
    name: "Domino's",
    menu: ["Pizza", "Pasta", "Wings"],
    price: 0,
    eta: "15-25 mins",
    image: null,
    metadata: { rating: 4.3, reviews: 200 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "food-kfc",
    service_type: "food",
    name: "KFC",
    menu: ["Bucket", "Zinger Burger", "Fries"],
    price: 0,
    eta: "20-30 mins",
    image: null,
    metadata: { rating: 4.4, reviews: 350 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "food-tastee",
    service_type: "food",
    name: "Tastee Fried Chicken",
    menu: ["Chicken Sandwich", "Spicy Wings", "Coleslaw"],
    price: 0,
    eta: "18-28 mins",
    image: null,
    metadata: { rating: 4.2, reviews: 180 },
    createdAt: new Date().toISOString(),
  },

  // ---- Parcel ----
  {
    city: "Lagos",
    serviceId: "parcel-dhl",
    service_type: "parcel",
    name: "DHL",
    parcelSizes: ["Small", "Medium", "Large", "Extra Large"],
    deliverySpeeds: ["Standard", "Express", "Same Day"],
    price: 0,
    eta: "1-3 days",
    image: null,
    metadata: { rating: 4.7, reviews: 500 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "parcel-fedex",
    service_type: "parcel",
    name: "FedEx",
    parcelSizes: ["Small", "Medium", "Large"],
    deliverySpeeds: ["Standard", "Express"],
    price: 0,
    eta: "1-4 days",
    image: null,
    metadata: { rating: 4.6, reviews: 400 },
    createdAt: new Date().toISOString(),
  },

  // ---- Grocery ----
  {
    city: "Lagos",
    serviceId: "grocery-fruits-vegetables",
    service_type: "grocery",
    name: "Fruits & Vegetables",
    items: ["Apples", "Tomatoes", "Bananas", "Carrots", "Onions"],
    price: 0,
    eta: "1-2 days",
    image: null,
    metadata: { rating: 4.5, reviews: 250 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "grocery-staples",
    service_type: "grocery",
    name: "Staples",
    items: ["Rice", "Beans", "Yam", "Spaghetti", "Cooking Oil"],
    price: 0,
    eta: "1-2 days",
    image: null,
    metadata: { rating: 4.4, reviews: 300 },
    createdAt: new Date().toISOString(),
  },
  {
    city: "Lagos",
    serviceId: "grocery-snacks",
    service_type: "grocery",
    name: "Snacks",
    items: ["Chips", "Biscuits", "Chocolate", "Nuts", "Popcorn"],
    price: 0,
    eta: "1-2 days",
    image: null,
    metadata: { rating: 4.3, reviews: 180 },
    createdAt: new Date().toISOString(),
  },
];

module.exports = DUMMY_SERVICES;
